/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -a core/mpris_player -c MprisPlayer -i core/mpris1.h -l mpris::Mpris1Player /home/mystte/rendu/audiowire-dev/src/dbus/org.freedesktop.MediaPlayer.player.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MPRIS_PLAYER_H_1366756077
#define MPRIS_PLAYER_H_1366756077

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "core/mpris1.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.MediaPlayer
 */
class MprisPlayer: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.MediaPlayer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.MediaPlayer\">\n"
"    <method name=\"Pause\"/>\n"
"    <method name=\"Stop\"/>\n"
"    <method name=\"Play\"/>\n"
"    <method name=\"Prev\"/>\n"
"    <method name=\"Next\"/>\n"
"    <method name=\"Repeat\">\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"GetStatus\">\n"
"      <arg direction=\"out\" type=\"(iiii)\"/>\n"
"      <annotation value=\"DBusStatus\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"VolumeSet\">\n"
"      <arg direction=\"in\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"VolumeGet\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"PositionSet\">\n"
"      <arg direction=\"in\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"PositionGet\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"GetMetadata\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"GetCaps\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <signal name=\"TrackChange\">\n"
"      <arg type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"    <signal name=\"StatusChange\">\n"
"      <arg type=\"(iiii)\"/>\n"
"      <annotation value=\"DBusStatus\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"    <signal name=\"CapsChange\">\n"
"      <arg type=\"i\"/>\n"
"    </signal>\n"
"    <!-- NB: Amarok extensions to the mpris spec -->\n"
"    <method name=\"VolumeUp\">\n"
"      <arg direction=\"in\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"VolumeDown\">\n"
"      <arg direction=\"in\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"Mute\"/>\n"
"    <method name=\"ShowOSD\"/>\n"
"  </interface>\n"
        "")
public:
    MprisPlayer(mpris::Mpris1Player *parent);
    virtual ~MprisPlayer();

    inline mpris::Mpris1Player *parent() const
    { return static_cast<mpris::Mpris1Player *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int GetCaps();
    QVariantMap GetMetadata();
    DBusStatus GetStatus();
    void Mute();
    void Next();
    void Pause();
    void Play();
    int PositionGet();
    void PositionSet(int in0);
    void Prev();
    void Repeat(bool in0);
    void ShowOSD();
    void Stop();
    void VolumeDown(int in0);
    int VolumeGet();
    void VolumeSet(int in0);
    void VolumeUp(int in0);
Q_SIGNALS: // SIGNALS
    void CapsChange(int in0);
    void StatusChange(DBusStatus in0);
    void TrackChange(const QVariantMap &in0);
};

#endif
