/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -a core/mpris2_playlists -c Mpris2Playlists -i core/mpris2.h -l mpris::Mpris2 /home/mystte/rendu/audiowire-dev/src/dbus/org.mpris.MediaPlayer2.Playlists.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MPRIS2_PLAYLISTS_H_1366756078
#define MPRIS2_PLAYLISTS_H_1366756078

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "core/mpris2.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.mpris.MediaPlayer2.Playlists
 */
class Mpris2Playlists: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.mpris.MediaPlayer2.Playlists")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.mpris.MediaPlayer2.Playlists\">\n"
"    <property access=\"read\" type=\"u\" name=\"PlaylistCount\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"Orderings\"/>\n"
"    <property access=\"read\" type=\"(b(oss))\" name=\"ActivePlaylist\">\n"
"      <annotation value=\"MaybePlaylist\" name=\"com.trolltech.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <method name=\"ActivatePlaylist\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"PlaylistId\"/>\n"
"    </method>\n"
"    <method name=\"GetPlaylists\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"Index\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"MaxCount\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"Order\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"ReverseOrder\"/>\n"
"      <arg direction=\"out\" type=\"a(oss)\" name=\"Playlists\"/>\n"
"      <annotation value=\"MprisPlaylistList\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <signal name=\"PlaylistChanged\">\n"
"      <arg type=\"(oss)\" name=\"Playlist\"/>\n"
"      <annotation value=\"MprisPlaylist\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"    <annotation value=\"MaybePlaylist\" name=\"com.trolltech.QtDBus.QtTypeName\"/>\n"
"  </interface>\n"
        "")
public:
    Mpris2Playlists(mpris::Mpris2 *parent);
    virtual ~Mpris2Playlists();

    inline mpris::Mpris2 *parent() const
    { return static_cast<mpris::Mpris2 *>(QObject::parent()); }

public: // PROPERTIES
    Q_PROPERTY(MaybePlaylist ActivePlaylist READ activePlaylist)
    MaybePlaylist activePlaylist() const;

    Q_PROPERTY(QStringList Orderings READ orderings)
    QStringList orderings() const;

    Q_PROPERTY(uint PlaylistCount READ playlistCount)
    uint playlistCount() const;

public Q_SLOTS: // METHODS
    void ActivatePlaylist(const QDBusObjectPath &PlaylistId);
    MprisPlaylistList GetPlaylists(uint Index, uint MaxCount, const QString &Order, bool ReverseOrder);
Q_SIGNALS: // SIGNALS
    void PlaylistChanged(MprisPlaylist Playlist);
};

#endif
