/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -a core/mpris_tracklist -c MprisTrackList -i core/mpris1.h -l mpris::Mpris1TrackList /home/mystte/rendu/audiowire-dev/src/dbus/org.freedesktop.MediaPlayer.tracklist.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "core/mpris_tracklist.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MprisTrackList
 */

MprisTrackList::MprisTrackList(mpris::Mpris1TrackList *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MprisTrackList::~MprisTrackList()
{
    // destructor
}

int MprisTrackList::AddTrack(const QString &in0, bool in1)
{
    // handle method call org.freedesktop.MediaPlayer.AddTrack
    return parent()->AddTrack(in0, in1);
}

void MprisTrackList::DelTrack(int in0)
{
    // handle method call org.freedesktop.MediaPlayer.DelTrack
    parent()->DelTrack(in0);
}

int MprisTrackList::GetCurrentTrack()
{
    // handle method call org.freedesktop.MediaPlayer.GetCurrentTrack
    return parent()->GetCurrentTrack();
}

int MprisTrackList::GetLength()
{
    // handle method call org.freedesktop.MediaPlayer.GetLength
    return parent()->GetLength();
}

QVariantMap MprisTrackList::GetMetadata(int in0)
{
    // handle method call org.freedesktop.MediaPlayer.GetMetadata
    return parent()->GetMetadata(in0);
}

void MprisTrackList::PlayTrack(int in0)
{
    // handle method call org.freedesktop.MediaPlayer.PlayTrack
    parent()->PlayTrack(in0);
}

void MprisTrackList::SetLoop(bool in0)
{
    // handle method call org.freedesktop.MediaPlayer.SetLoop
    parent()->SetLoop(in0);
}

void MprisTrackList::SetRandom(bool in0)
{
    // handle method call org.freedesktop.MediaPlayer.SetRandom
    parent()->SetRandom(in0);
}


#include "core/mpris_tracklist.moc"
