/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -a core/mpris_player -c MprisPlayer -i core/mpris1.h -l mpris::Mpris1Player /home/mystte/rendu/audiowire-dev/src/dbus/org.freedesktop.MediaPlayer.player.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "core/mpris_player.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MprisPlayer
 */

MprisPlayer::MprisPlayer(mpris::Mpris1Player *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MprisPlayer::~MprisPlayer()
{
    // destructor
}

int MprisPlayer::GetCaps()
{
    // handle method call org.freedesktop.MediaPlayer.GetCaps
    return parent()->GetCaps();
}

QVariantMap MprisPlayer::GetMetadata()
{
    // handle method call org.freedesktop.MediaPlayer.GetMetadata
    return parent()->GetMetadata();
}

DBusStatus MprisPlayer::GetStatus()
{
    // handle method call org.freedesktop.MediaPlayer.GetStatus
    return parent()->GetStatus();
}

void MprisPlayer::Mute()
{
    // handle method call org.freedesktop.MediaPlayer.Mute
    parent()->Mute();
}

void MprisPlayer::Next()
{
    // handle method call org.freedesktop.MediaPlayer.Next
    parent()->Next();
}

void MprisPlayer::Pause()
{
    // handle method call org.freedesktop.MediaPlayer.Pause
    parent()->Pause();
}

void MprisPlayer::Play()
{
    // handle method call org.freedesktop.MediaPlayer.Play
    parent()->Play();
}

int MprisPlayer::PositionGet()
{
    // handle method call org.freedesktop.MediaPlayer.PositionGet
    return parent()->PositionGet();
}

void MprisPlayer::PositionSet(int in0)
{
    // handle method call org.freedesktop.MediaPlayer.PositionSet
    parent()->PositionSet(in0);
}

void MprisPlayer::Prev()
{
    // handle method call org.freedesktop.MediaPlayer.Prev
    parent()->Prev();
}

void MprisPlayer::Repeat(bool in0)
{
    // handle method call org.freedesktop.MediaPlayer.Repeat
    parent()->Repeat(in0);
}

void MprisPlayer::ShowOSD()
{
    // handle method call org.freedesktop.MediaPlayer.ShowOSD
    parent()->ShowOSD();
}

void MprisPlayer::Stop()
{
    // handle method call org.freedesktop.MediaPlayer.Stop
    parent()->Stop();
}

void MprisPlayer::VolumeDown(int in0)
{
    // handle method call org.freedesktop.MediaPlayer.VolumeDown
    parent()->VolumeDown(in0);
}

int MprisPlayer::VolumeGet()
{
    // handle method call org.freedesktop.MediaPlayer.VolumeGet
    return parent()->VolumeGet();
}

void MprisPlayer::VolumeSet(int in0)
{
    // handle method call org.freedesktop.MediaPlayer.VolumeSet
    parent()->VolumeSet(in0);
}

void MprisPlayer::VolumeUp(int in0)
{
    // handle method call org.freedesktop.MediaPlayer.VolumeUp
    parent()->VolumeUp(in0);
}


#include "core/mpris_player.moc"
