/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p dbus/udisks /home/mystte/rendu/audiowire-dev/src/dbus/org.freedesktop.UDisks.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus/udisks.h"

/*
 * Implementation of interface class OrgFreedesktopUDisksInterface
 */

OrgFreedesktopUDisksInterface::OrgFreedesktopUDisksInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopUDisksInterface::~OrgFreedesktopUDisksInterface()
{
}


#include "dbus/udisks.moc"
