/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p dbus/wiimotedev /home/mystte/rendu/audiowire-dev/src/dbus/org.wiimotedev.deviceEvents.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef WIIMOTEDEV_H_1366756079
#define WIIMOTEDEV_H_1366756079

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.wiimotedev.deviceEvents
 */
class OrgWiimotedevDeviceEventsInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.wiimotedev.deviceEvents"; }

public:
    OrgWiimotedevDeviceEventsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgWiimotedevDeviceEventsInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void dbusWiimoteBatteryLife(uint in0, uchar in1);
    void dbusWiimoteConnected(uint id);
    void dbusWiimoteDisconnected(uint id);
    void dbusWiimoteGeneralButtons(uint id, qulonglong value);
};

#endif
