/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -p dbus/wiimotedev /home/mystte/rendu/audiowire-dev/src/dbus/org.wiimotedev.deviceEvents.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus/wiimotedev.h"

/*
 * Implementation of interface class OrgWiimotedevDeviceEventsInterface
 */

OrgWiimotedevDeviceEventsInterface::OrgWiimotedevDeviceEventsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgWiimotedevDeviceEventsInterface::~OrgWiimotedevDeviceEventsInterface()
{
}


#include "dbus/wiimotedev.moc"
